### PR TITLE
[WFLY-14238] FaceletsResourceResolver annotation is not taken into account

### PR DESCRIPTION
**Pull request by rmartinc**
Issue: https://issues.redhat.com/browse/WFLY-14238

The fix just adds the missing annotation (`javax.faces.view.facelets.FaceletsResourceResolver`) included in JSF 2.2+ to wildfly. Previously it was not there and the Jandex Annotation Provider does not return classes with this annotation inside a JSF app. The class is loaded programmatically (`loadClass`) because if not done this way there is a `NoClassDefFoundError` in the Jandex provider and the implementation defaults to the default JSF one. Test included.

@fjuma take a look when you have time.

### CODE REVIEW

File: jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java [hunk 1]
```diff
@@ -70,7 +70,10 @@
             stringToAnnoMap.put(FacesBehavior.class.getName(), FacesBehavior.class);
             stringToAnnoMap.put(FacesBehaviorRenderer.class.getName(), FacesBehaviorRenderer.class);
 
-            // Put JSF 2.2 annotations below this line if any new ones are to be scanned.  So far none.
+            // Put JSF 2.2+ annotations below this line if any new ones are to be scanned.
+            // Load the class to avoid a NoClassDefFoundError if it is not present in the impl
+            ClassLoader loader = AnnotationMap.class.getClassLoader();
+            addAnnotationIfPresent(loader, "javax.faces.view.facelets.FaceletsResourceResolver");
```
Comment (fjuma) [inline jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java:76]: Could use `FaceletsResourceResolver.class.getName()` here.

**Review by fjuma — COMMENTED** [review]
@rmartinc Thanks, looks good! I've just added one minor comment.

File: jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java (hunk 1 above)
Comment (rmartinc) [reply jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java:76]: `FaceletsResourceResolver` is not present in JSF 2.1 and 2.0. If it is imported a `NoClassDefFoundError` is thrown and the Jandex provider is not loaded (default JSF one is used, `DelegatingAnnotationProvider` in 2.1 for example). I discovered this when I did some tests with the multi-jsf. So I decided to do a `loadClass` and don't import the class at all, to make it work with old 2.0 and 2.1 impls. WDYT?

Comment (fjuma) [reply jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java:76]: Ah, ok, that's fine then.

**Review by fjuma — APPROVED** [review]

File: jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java (hunk 1 above)
Comment (rmartinc) [reply jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java:76]: I tested with ee9 too because of the name, and it's translated OK. :smiley:

Comment (fjuma) [reply jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java:76]: Great, was just thinking about that. Thanks very much, Ricardo!

Comment (bstansberry) [reply jsf/injection/src/main/java/org/jboss/as/jsf/injection/AnnotationMap.java:76]: :+
