### PR TITLE
WFLY-11875 Update javassist from 3.23.1-GA to 3.24.1-GA

### PR DESCRIPTION
**Pull request by soul2zimate**
https://issues.jboss.org/browse/WFLY-11875 Update javassist from 3.23.1-GA to 3.24.1-GA

### CODE REVIEW

**Comment by kabir** [comment]
@scottmarlow Hibernate is probably the main user - please approve

**Comment by scottmarlow** [comment]
@kabir @jamezp looks like this won't work with Hibernate 5.3, as I tried to build/test the Hibernate ORM 5.3 branch with 3.24.1-GA and I get compile failure:

> /home/smarlow/work/hibernate5/hibernate-core/src/main/java/org/hibernate/bytecode/internal/javassist/BulkAccessorFactory.java:74: error: no suitable method found for toClass(ClassFile,ClassLoader,ProtectionDomain)
>                         beanClass = FactoryHelper.toClass( classfile, loader, getDomain() );
>                                                  ^
>     method FactoryHelper.toClass(ClassFile,ClassLoader) is not applicable
>       (actual and formal argument lists differ in length)
>     method FactoryHelper.toClass(ClassFile,Class<?>,ClassLoader,ProtectionDomain) is not applicable
>       (actual and formal argument lists differ in length)
>     method FactoryHelper.toClass(ClassFile,Lookup) is not applicable
>       (actual and formal argument lists differ in length)
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 1 error
> 
> > Task :hibernate-core:compileJava FAILED
> 
> FAILURE: Build failed with an exception.
> 

@gbadner fyi ^

Looks like Hibernate ORM 5.3 would have to change to call the new signature:
[javassist.util.proxy.FactoryHelper#toClass differently](https://github.com/jboss-javassist/javassist/commit/6320bc4e14350af392b285b1b1ea312673625b21#diff-ddec044ab147cbae4c1402c4be2aacacR127)
`beanClass = FactoryHelper.toClass( classfile, null, loader, getDomain() ); `

Or create a PR to javassist for the next javassist release, one or the other.

**Comment by bstansberry** [comment]
Closing, as this does not work with current Hibernate. Upgrade should come along with a Hibernate upgrade, if Hibernate wants to change.

TBH this sounds like something Javassist should correct since changing an API method signature in a micro is usually not wanted. Since the new param can be null, perhaps the old method can be restored, calling the new with 'null' for the new param?

**Comment by soul2zimate** [comment]
FYI, the change is made in a minor release 3_24_0_ga for java 11 support.
However, the javassist master branch is going to be 3.25-GA (it seems there isn't any plan for a major version development)
